GSA-TTS/forms

- packages/design/src/Form/PromptSegment/SubmissionConfirmation/SubmissionConfirmation.stories.tsx
#48 introduced a bug with Storybook, with a missing story for `SubmissionConfirmation` - this PR adds one.
> Add missing Storybook story for SubmissionConfirmation

- .github/workflows/deploy.yml
Hardcode the ghcr.io path, rather than mess with lack of string processing in Github Actions
> Hardcode the ghcr.io path

- packages/design/src/Form/components/Checkbox/Checkbox.tsx
- packages/design/src/FormManager/FormEdit/components/CheckboxPatternEdit.test.tsx
- packages/design/src/FormManager/FormEdit/components/InputPatternEdit.tsx
Checkbox inputs did not reflect checked state in the UI due to markup order. Changed markup for compatibility with USWDS
> Input check

- packages/design/src/FormManager/FormEdit/components/CheckboxPatternEdit.test.tsx
- packages/design/src/FormManager/FormEdit/components/InputPatternEdit.tsx
Values for max length and initial value were being wiped out in the form edit UI when opened and closed.
> Fix bug with input field not populating previous and default values on the FormEdit UI

- packages/forms/src/patterns/page/prompt.ts
Fixes page title saving error. There were certain situations where the patterns array would have an item with an `""`, causing the `createPromptForPattern` check to fail.
> Filter out patternIds with empty string values.

- packages/design/src/FormManager/FormEdit/formEditStyles.module.css
- packages/design/src/FormManager/index.tsx
- I updated the content of the configure and publish pages
[PR Preview](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/add-content-to-configure-publish-pages/)
> Add content to configure publish pages

- packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/DraggableList.tsx
- packages/design/src/FormManager/FormEdit/store.ts
- packages/forms/src/builder/index.ts
So edit mode isn't inadvertently triggered while reordering via drag, prevent onFocus event from propagating from dnd handles to parent edit components.
> Prevent onFocus event from propagating from dnd handles to parent edit components

- packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/DraggableList.tsx
Key on unique pattern ID rather than child index, so focus isn't lost on an item after reordering.
> Fix: Loss of focus after drag-and-drop

- packages/forms/src/documents/pdf/parsing-api.ts
To avoid PDF generation errors, comment out radio group outputs, temporarily.
> Comment out radio group outputs

- infra/cdktf.json
- infra/package.json
- infra/src/lib/app-stack.ts
Acquire Cloud.gov secrets from AWS parameter store via a Terraform data lookup.
Context: this allows us to easily have separate service accounts for each deployment environment, and rotate credentials.
> Store Cloud.gov secrets in AWS parameter store

- .github/workflows/_terraform-apply.yml
- .github/workflows/_terraform-plan-pr-comment.yml
- .github/workflows/_validate.yml
- README.md
- packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
- packages/design/src/FormManager/FormEdit/components/PageEdit.tsx
- packages/design/src/FormManager/FormEdit/components/PageSetEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/DraggableList.tsx
- packages/design/src/FormManager/FormEdit/formEditStyles.module.css
- packages/design/src/test-form.ts
- Updated the draggable list focus to be the entire container rather than just the handle.
-  Updated the Read me.
- Attempted to fix the page number in the Pate title area but commented out my changes because I couldn't get them to past the storybook test. I need to consult with @danielnaab about this.
[PR Preview](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/update-focus-on-drag-list-ui-updates/)
> Updated the focus on the drag list and UI updates

- .github/workflows/_validate.yml
- package.json
- pnpm-lock.yaml
- Updated github actions used in the `_validate.yaml` file to fix deprecation notices.
- Updated pnpm version used in `_validate.yaml` to resolve build errors in coverage report
- Remove deprecated `@vitest/coverage-c8` package from project - coverage was moved to https://www.npmjs.com/package/@vitest/coverage-v8, which is actively maintained.
> Remove deprecated dependency and update action versions

- packages/common/src/locales/en/app.ts
- packages/design/src/Form/components/DateOfBirth/DateOfBirth.stories.tsx
- packages/design/src/Form/components/DateOfBirth/DateOfBirth.test.tsx
- packages/design/src/Form/components/DateOfBirth/DateOfBirth.tsx
- packages/design/src/Form/components/DateOfBirth/index.tsx
- packages/design/src/Form/components/SelectDropdown/SelectDropdown.tsx
- packages/design/src/Form/components/index.tsx
- packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
- packages/design/src/FormManager/FormEdit/components/DateOfBirthPatternEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/DateOfBirthPatternEdit.test.tsx
- packages/design/src/FormManager/FormEdit/components/DateOfBirthPatternEdit.tsx
- packages/design/src/FormManager/FormEdit/components/index.ts
- packages/design/src/FormManager/FormEdit/formEditStyles.module.css
- packages/forms/package.json
- packages/forms/src/components.ts
- packages/forms/src/pattern.ts
- packages/forms/src/patterns/date-of-birth/date-of-birth.test.ts
- packages/forms/src/patterns/date-of-birth/date-of-birth.ts
- packages/forms/src/patterns/index.ts
- packages/forms/src/set-value.d.ts
- pnpm-lock.yaml
Created  Date of Birth Pattern for Forms Users.
Created  Date of Birth Pattern Edit for Form Builders.
Added unit tests for Date of Birth Pattern.
Refactored and added value aggregation hook to handle structured and single values in form validation
> feat: create date of birth pattern tckt-361

- documents/podman-integration.md
**Pipeline Failure at Deploy Stage**
We are currently experiencing a pipeline failure during the Deploy stage: [See the failing action run](https://github.com/GSA-TTS/forms/actions/runs/11710007835/job/32617676538).
**Suspected Cause**
The failure is likely due to a recent change in my git username from kalasgarov to Khayal Alasgarov. This could be affecting the pipeline's ability to access resources.
**Changes in this PR**
To address this issue, I have made a minor modification to the README file by removing some whitespace. This change is intended to retrigger the build process with the updated username once the PR is merged.
> chore: remove white space in a doc to rebuild the main branch

- packages/design/src/Form/components/DateOfBirth/DateOfBirth.tsx
- packages/design/src/Form/components/EmailInput/EmailInput.tsx
- packages/design/src/Form/components/PhoneNumber/PhoneNumber.tsx
- packages/design/src/Form/components/SelectDropdown/SelectDropdown.tsx
Addressed some accessibility issues for single field components.
Improved error handling for single field components.
> feat: improve accessibility for single field components tckt-393

- packages/database/migrations/20241031103354_form_documents_table.mjs
Use TEXT column type for `extract` column in `form_documents` table, rather than a 255-character string.
> Bugfix: form_documents column size

- README.md
- package.json
Uses git plumbing to add a command at the workspace root to clean modules since there have been times when we needed to do so.
> Add command to recursively clean node_modules directory

- .github/workflows/_terraform-apply.yml
- .github/workflows/_terraform-plan-pr-comment.yml
- .github/workflows/_validate.yml
We had discussed making the terraform install action reusable. However, there seems to be an issue where you can't have multiple uses in github actions where the call chain is file A -> uses file B -> uses file C without involving an artifact. This switches to use the Hashicorp-authored actions/setup-terraform which provides the artifact behavior and to gets around the structuring issue of our current action.
- update cache action to v4
- use setup-terraform action
> Reusable Terraform Action

- .husky/pre-commit
- package.json
Without the setting env var `CI`, the storybook browser tests kept the web socket connection open indefinitely, causing our pre-commit hooks to never exit and blocking commits unless we ran the commit command with --no-verify.
The `CI` var is set by default on the GH actions pipeline, but we need to set it explicitly for compatibility with local developer environments in the `test:ci` command.
> fix issue where pnpm test was not terminating on test completion

- packages/common/src/locales/en/app.ts
- packages/design/src/Form/components/TextArea/TextArea.stories.tsx
- packages/design/src/Form/components/TextArea/index.tsx
- packages/design/src/Form/components/index.tsx
- packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
- packages/design/src/FormManager/FormEdit/components/TextAreaPatternEdit/TextAreaPattermEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/TextAreaPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/index.ts
- packages/forms/src/components.ts
- packages/forms/src/patterns/index.ts
- packages/forms/src/patterns/text-area/text-area.test.ts
- packages/forms/src/patterns/text-area/text-area.ts
Created TextArea (Long Answer) Pattern for Forms Users.
Created TextArea (Long Answer) Pattern Edit for Form Builders.
Added TextArea (Long Answer) schema config and user input validation logic.
Added unit tests for TextArea (Long Answer) config file.
Added vitests (story tests) for TextArea (Long Answer) Pattern.
> feat: create textarea (long answer) component tckt-399

- .github/workflows/deploy.yml
- packages/server/src/pages/index.astro
Cosmetic - add a "require log in" message to view the form manager UI.
> Server log in UI

- apps/server-doj/src/server.ts
This PR adds `marco.pineda@gsa.gov` to the User config.
> chore: add marco.pineda email to the user config

- e2e/src/create.spec.ts
- packages/common/src/locales/en/app.ts
- packages/design/src/Form/components/RadioGroup/RadioGroup.tsx
- packages/design/src/Form/components/SelectDropdown/SelectDropdown.tsx
- packages/design/src/FormManager/FormEdit/components/RadioGroupPatternEdit/RadioGroupPatternEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/RadioGroupPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/SelectDropdownPatternEdit/SelectDropdownPatternEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/SelectDropdownPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/formEditStyles.module.css
- packages/forms/src/builder/builder.test.ts
- packages/forms/src/components.ts
- packages/forms/src/documents/pdf/parsing-api.ts
- packages/forms/src/patterns/radio-group.ts
- packages/forms/src/patterns/select-dropdown/select-dropdown.ts
**Overview**
Updated the choice component UI for `radio-group`, `select-dropdown`.
**Key Changes**
> Adds hint field and required field for components
> Updates Copy for choice component fields
> Refactors the UI to reflect the hint and required fields in components.
> Refactors the choice schema to account for options
> Adds styles for Figma parity
> Updates Tests
**Figma Reference**
https://www.figma.com/design/RAm1GWbVTdBpzlmaLL6pLO/Forms-Platform?node-id=3198-21604&p=f&t=RXcqnhASJeRwxx5u-0
**Ticket Reference**
These changes are part of the https://github.com/GSA-TTS/forms/issues/454.
**Note**:
Checkbox changes will be done in separate ticket
> feat: update radio-group and select-dropdown component UI

- packages/server/src/components/DOJFooter.astro
- packages/server/src/components/DOJHeader.astro
- packages/server/src/components/Footer.astro
- packages/server/src/components/Header.astro
**Overview**
This PR adds the DOJ demo header and footer to the server app
**Screen shots**
Desktop:
Mobile:
> Add DOJ demo header and footer to server app

- packages/design/src/FormManager/FormEdit/components/RadioGroupPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/SelectDropdownPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/common/hooks.ts
*Overview*
This PR adds custom hook logic for deleting a choice option and updating an option label. This work also addresses the conversation @ethangardner and I discussed in this [PR](https://github.com/GSA-TTS/forms/pull/586#pullrequestreview-2741097986) comment thread. 
TCKT reference : [593](https://github.com/orgs/GSA-TTS/projects/17/views/8?pane=issue&itemId=105109270&issue=GSA-TTS%7Cforms%7C593)
> refactor: adds custom choice option hook for option delete and update label

- packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
- packages/design/src/FormManager/FormEdit/components/FieldsetEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/RepeaterPatternEdit.tsx
**Key Changes:**
> Created a reusable button component to add supplementary information or instructions.
> Integrated the AddInformationOrInstructionsButton to Fieldset Component.
> Integrated the AddInformationOrInstructionsButton to Repeater Component.
**Ticket Reference:**
[TCKT-415](https://github.com/GSA-TTS/forms/issues/415)
> feat: add button for Add supplementary information or instructions in Repeater and Fieldset components TCKT-415

- packages/design/src/Form/components/PageSet/PageSet.stories.tsx
- packages/design/src/FormManager/FormDelete/FormDelete.stories.tsx
- packages/design/src/FormManager/FormDocumentImport/DocumentImporter/DocumentImporter.stories.tsx
- packages/design/src/FormManager/FormEdit/FormEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/DraggableList.stories.tsx
- packages/design/src/FormManager/FormEdit/components/PageSetEdit/PageSetEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/common/story-helper.tsx
- packages/design/src/FormManager/FormList/CreateNew/PDFFileSelect.stories.tsx
- packages/design/src/FormManager/FormList/FormList.stories.tsx
- packages/design/src/FormManager/FormManagerLayout/FormManagerLayout.stories.tsx
- packages/design/src/FormManager/FormPreview/FormPreview.stories.tsx
- packages/design/src/FormManager/Notifications/Notifications.stories.tsx
- packages/design/src/test-form.ts
*Overview*
This PR attempts to refactor the methods used to create form test patterns and pages and addresses this [comment](https://github.com/GSA-TTS/forms/pull/600#discussion_r2039660967).
This refactor itself could be refactored to be a bit more SOLID. However, I didn't want to invest _too_ much time into this. While this PR an improvement and makes the creation process a bit more flexible, we do lose readability.
References [TCKT](https://github.com/orgs/GSA-TTS/projects/17/views/8?pane=issue&itemId=106095672&issue=GSA-TTS%7Cforms%7C603)
> Refactor: test form create page pattern

- packages/design/src/FormManager/FormEdit/components/CheckboxGroupPatternEdit/CheckboxGroupPatternEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/CheckboxGroupPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/DraggableList.tsx
- packages/design/src/FormManager/FormEdit/components/RadioGroupPatternEdit/RadioGroupPatternEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/RadioGroupPatternEdit/index.tsx
- packages/design/src/FormManager/FormEdit/components/SelectDropdownPatternEdit/SelectDropdownPatternEdit.stories.tsx
- packages/design/src/FormManager/FormEdit/components/SelectDropdownPatternEdit/index.tsx
*Overview*
This PR:
- adds the ability for users to drag and drop to reorder choice option fields.
- adds style: a new presentation attribute similar to "compact" called "compact-center"  
*Tests*
- updates stories to include field deletion
*Screencapture*
https://github.com/user-attachments/assets/7e0a1699-6559-41c2-9ff9-812f1386b636
References [TCKT](https://github.com/orgs/GSA-TTS/projects/17/views/8?pane=issue&itemId=104924800&issue=GSA-TTS%7Cforms%7C587)
> feat: adds ability to reorder choice option components on Choice edit stage

- packages/design/src/FormManager/FormManager.tsx
- packages/design/src/FormManager/FormManagerLayout/FormManagerLayout.tsx
- packages/design/src/FormManager/FormManagerLayout/TopNavigation.tsx
****Key Changes:****
- Updated the breadcrumb to display "Edit form" in preview mode, linking back to the edit view.
- Removed the step indicator in preview mode as it is not relevant.
- Updated the button text to "Exit Preview" in preview mode, linking back to the edit view.
- Refactored logic to simplify and ensure consistent header behavior across preview and non-preview modes.
**BEFORE:**
**Preview Mode:**
**Non-preview/Edit mode:**
**AFTER:**
**Preview Mode:**
**Non-preview/Edit mode:**
> fix: resolve the issue with incorrect header for forms preview TCKT-566
