apps/spotlight/src/pages/index.astro
packages/design/sass/styles.scss
packages/design/src/Form/ActionBar/index.tsx
packages/design/src/FormManager/FormEdit/FormElementEdit.tsx
packages/design/src/FormManager/FormEdit/Preview.tsx
packages/design/src/FormManager/FormEdit/index.tsx
packages/design/src/FormManager/FormList/index.tsx
packages/design/src/FormManager/internalPageTopNav.tsx
packages/design/src/config/edit/InputElementEdit.tsx
packages/design/src/config/view/FormSummary/FormSummary.stories.tsx
packages/design/src/config/view/FormSummary/index.tsx
packages/design/src/config/view/TextInput/TestInput.stories.tsx
packages/design/src/config/view/TextInput/index.tsx

In this branch, I made the following changes:
- Updated the styles of the Edit Form Page
- Cleaned up the HTML in some of the related components
- Fixed a bug to get the required checkbox on the Edit page to work.
[PR Preview](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/update-styles-of-edit-page/)

Update styles of edit page

---

packages/design/src/config/view/SubmissionConfirmation/index.tsx
packages/forms/src/config/elements/form-summary.ts
packages/forms/src/pattern.ts

Style the submission confirmation pattern

---

packages/design/sass/styles.scss
packages/design/src/Form/index.tsx
packages/design/src/FormManager/FormEdit/Preview.tsx
packages/design/src/config/view/Fieldset/index.tsx
packages/design/src/config/view/SubmissionConfirmation/index.tsx

This tweaks a number of small things for the upcoming FFP demo. #21

Last-minute demo tweaks

---

packages/design/src/FormManager/FormEdit/AddPattern.tsx
packages/design/src/FormManager/FormEdit/FormEdit.stories.tsx
packages/design/src/FormManager/FormEdit/index.tsx
packages/design/src/FormManager/FormEdit/store.tsx
packages/design/src/config/edit/index.ts
packages/forms/src/builder/builder.test.ts
packages/forms/src/builder/index.ts
packages/forms/src/documents/document.ts
packages/forms/src/index.ts
packages/forms/src/pattern.ts
packages/forms/src/patterns/fieldset.ts
packages/forms/src/patterns/form-summary.ts
packages/forms/src/patterns/input.ts
packages/forms/src/patterns/paragraph.ts
packages/forms/src/patterns/sequence.ts

As part of the Kansas name change form, implement #87

"Add pattern" function added to builder UI

---

packages/design/src/FormManager/FormEdit/FormEdit.stories.tsx
packages/design/src/FormManager/FormList/CreateNew/PDFFileSelect.test.tsx
packages/design/src/config/view/SubmissionConfirmation/SubmissionConfirmation.stories.tsx
packages/design/src/config/view/TextInput/TestInput.stories.tsx

Address cleanup

---

packages/design/src/FormManager/FormEdit/PreviewPattern.tsx
packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/DraggableList.tsx
packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/index.tsx
packages/design/src/FormManager/FormEdit/store.ts
packages/forms/src/builder/builder.test.ts
packages/forms/src/builder/index.ts
packages/forms/src/session.ts

This fixes a couple of issues for #77:
- drag-and-drop #150 
- add patterns to the currently selected page, rather than always the first page
- scroll to focused pattern

Misc UI behavior improvements

---

packages/design/src/FormManager/FormEdit/components/RadioGroupPatternEdit.tsx

hide option id, fix illegal default id value

hide-radio-optionid

---

apps/spotlight/src/components/Header.astro
apps/spotlight/src/components/UsaBanner.astro
packages/common/src/locales/en/app.ts
packages/design/sass/_uswds-custom-styles.scss
packages/design/src/Form/ActionBar/index.tsx
packages/design/src/Form/components/PageSet/PageMenu/PageMenu.tsx
packages/design/src/Form/components/PageSet/PageMenu/pageMenuStyles.module.css
packages/design/src/Form/index.tsx
packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
packages/design/src/FormManager/FormEdit/components/PageEdit.tsx
packages/design/src/FormManager/FormEdit/components/ParagraphPatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/formEditStyles.module.css
packages/design/src/FormManager/FormEdit/index.tsx
packages/design/src/FormManager/FormManagerLayout/TopNavigation.tsx
packages/design/src/FormManager/FormManagerLayout/index.tsx
packages/forms/src/patterns/paragraph.ts
packages/forms/src/patterns/radio-group.ts

- Staging banner at top of app on all screens
- Update question text name in dropdown menu
- Add submit button to Preview
- Add desktop style to Preview form
- Make side navs sticky
- Remove page, page set, sequence and physical address from the "Add Questions" list
[PR Preview](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/pre-demo-ui-updates/)

Pre demo UI updates

---

packages/design/src/FormManager/FormDelete/index.tsx

- Show user name they recognize, not id they don't
- hide json form data behind details dropdown
- pretty format json data
[PR Review Build](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/delete-page-style/)

Clean up delete page

---

packages/design/src/FormManager/FormEdit/formEditStyles.module.css
packages/design/src/FormManager/index.tsx

- I added content to the configure and publish pages
[PR Preview](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/add-content-to-configure-publish-pages/)

Added content to the configure and publish pages

---

packages/design/src/FormManager/FormDelete/index.tsx
packages/design/src/FormManager/index.tsx

Code formatting. Will move this into a precommit hook or linting step

format code with prettier

---

packages/design/src/FormManager/FormEdit/components/PreviewSequencePattern/DraggableList.tsx

- The drag effect of the draggable items were updated so that there's a shadow overlay and a drop zone. 
[PR Preview](https://federalist-16f2aca2-467c-449f-b725-5f1a0bd22dcd.sites.pages.cloud.gov/preview/gsa-tts/atj-platform/fix-draggable-list-animation-effect/)

Updated the Drag effect in the Draggable list

---

.github/workflows/deploy.yml

This fixes an issue discovered when merging the prior #231 to main.

Bugfix: Be explicit about deploy arguments

---

.github/workflows/_playwright.yml
.github/workflows/deploy.yml
.github/workflows/run-tests.yml
documents/adr/0010-end-to-end-testing.md

Workflow succeeded on a branch but failed when merged to main.

debugging issue on main

---

.github/workflows/_playwright.yml
.github/workflows/run-tests.yml

Dynamically set endpoint based on the type of action.

End to end tests

---

.github/ISSUE_TEMPLATE/risk.md

New template for managing risks within GitHub, with specific fields to complete.

Create new risk issue template

---

README.md
documents/diagram.md
documents/doj-diagram.md

View the diagram here: https://github.com/GSA-TTS/atj-platform/pull/345/files?short_path=078e0dc#diff-078e0dc3ea6498fad50041f606743f8042f66bfca24d665f46d84fce632c834a

Add c4-like diagram in Mermaid format

---

apps/server-doj/src/server.ts
apps/server-kansas/src/server.ts

Added my gsa email address to list of authorized user list in couple server files.

chore: update server file to add email address for khayal to authorized users list

---

packages/common/src/locales/en/app.ts
packages/design/src/Form/components/EmailInput/EmailInput.stories.tsx
packages/design/src/Form/components/EmailInput/EmailInput.test.tsx
packages/design/src/Form/components/EmailInput/EmailInput.tsx
packages/design/src/Form/components/EmailInput/index.tsx
packages/design/src/Form/components/index.tsx
packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
packages/design/src/FormManager/FormEdit/components/DateOfBirthPatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/EmailInputPatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/EmailInputPatternEdit.test.tsx
packages/design/src/FormManager/FormEdit/components/EmailInputPatternEdit.tsx
packages/design/src/FormManager/FormEdit/components/index.ts
packages/design/src/FormManager/FormEdit/formEditStyles.module.css
packages/design/src/FormManager/FormEdit/images/email-icon.svg
packages/forms/src/components.ts
packages/forms/src/patterns/date-of-birth/date-of-birth.test.ts
packages/forms/src/patterns/email-input/email-input.test.ts
packages/forms/src/patterns/email-input/email-input.ts
packages/forms/src/patterns/index.ts

Created Email Input Pattern for Forms Users.
Created Email Input Pattern Edit for Form Builders.
Added unit tests for Email Input config file.

feat: create email input pattern tckt-362

---

packages/forms/src/blueprint.ts
packages/forms/src/builder/index.ts
packages/forms/src/builder/parse-form.ts
packages/forms/src/components.ts
packages/forms/src/context/browser/form-repo.ts
packages/forms/src/context/browser/session-repo.ts
packages/forms/src/pattern.ts
packages/forms/src/repository/add-document.ts
packages/forms/src/repository/add-form.ts
packages/forms/src/repository/delete-form.ts
packages/forms/src/repository/get-document.ts
packages/forms/src/repository/get-form-list.ts
packages/forms/src/repository/get-form-session.ts
packages/forms/src/repository/get-form.ts
packages/forms/src/repository/save-form.ts
packages/forms/src/repository/upsert-form-session.ts
packages/forms/src/services/add-form.ts
packages/forms/src/services/delete-form.ts
packages/forms/src/services/get-form-list.ts
packages/forms/src/services/get-form-session.ts
packages/forms/src/services/get-form.ts
packages/forms/src/services/index.ts
packages/forms/src/services/initialize-form.ts
packages/forms/src/services/save-form.ts
packages/forms/src/services/submit-form.ts
packages/forms/src/session.ts
packages/forms/src/submission.ts
packages/forms/src/util/base64.ts
packages/forms/src/util/zod.ts

- add jsdoc comments for the forms package builder, context, and repository files
- add jsdoc comments to forms package

Add jsdoc comments to forms package

---

Dockerfile
infra/cdktf/src/lib/cloud.gov/node-astro.ts

Update Dockerfile to node 22 and set a 5 minute timeout on the Cloudfoundry app creation.

Update to node 22 in deployed environment

---

packages/common/src/locales/en/app.ts
packages/design/src/Form/components/Name/Name.stories.tsx
packages/design/src/Form/components/Name/index.tsx
packages/design/src/Form/components/index.tsx
packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
packages/design/src/FormManager/FormEdit/components/NamePatternEdit/NamePatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/NamePatternEdit/index.tsx
packages/design/src/FormManager/FormEdit/components/index.ts
packages/design/src/FormManager/FormEdit/formEditStyles.module.css
packages/design/src/FormManager/FormEdit/images/name-icon.svg
packages/forms/src/components.ts
packages/forms/src/pattern.ts
packages/forms/src/patterns/index.ts
packages/forms/src/patterns/name/index.ts
packages/forms/src/patterns/name/name.test.ts
packages/forms/src/patterns/repeater/submit.ts
packages/forms/src/util/zod.ts

Name Pattern: https://github.com/GSA-TTS/forms/issues/78
Created Name Pattern for Form Users.
Created Edit component for Name Pattern.
Implemented Name Pattern config schema and user input validation logic.
Added unit tests for Name Pattern config file.
Added vitests (stories) for Name Pattern.

feat: create name pattern TCKT-78

---

packages/design/src/FormManager/FormManagerLayout/FormManagerLayout.stories.tsx
packages/design/src/FormManager/FormManagerLayout/TopNavigation.tsx
packages/design/src/FormManager/index.tsx

This PR address the following [issue](https://github.com/orgs/GSA-TTS/projects/17/views/8?pane=issue&itemId=93547110&issue=GSA-TTS%7Cforms%7C440) and updates the visual progress indicator by:

Update visual progress indicator 

---

packages/design/src/FormManager/FormEdit/formEditStyles.module.css

This PR addresses issue: #[417](https://github.com/orgs/GSA-TTS/projects/17/views/8?pane=issue&itemId=91397592&issue=GSA-TTS%7Cforms%7C417) 
Desktop Demo
https://github.com/user-attachments/assets/1e491b4f-ea85-4c92-a484-8371734a0496
Mobile Demo
https://github.com/user-attachments/assets/2274d307-a4ed-4d30-94d0-8db03a0b6183

Adds ability to scroll on Question/Element dropdown menu

---

packages/forms/src/patterns/social-security-number/social-security-number.test.ts
packages/forms/src/patterns/social-security-number/social-security-number.ts

**Overview**
Refined the validation language for the Social Security Number (SSN) input and updating the corresponding test cases to reflect these changes.
**Key Changes**
***Validation Language Update:***
> Refactored the validation logic for SSN input to use a consistent error message, enhancing clarity and user experience.
> Test Updates:
> Updated SSN test cases to align with the new validation language, ensuring that all tests accurately reflect the updated error messaging.
**Ticket Reference**
These changes are part of the https://github.com/GSA-TTS/forms/issues/461.

refactor: update validation language for SSN input TCKT-461

---

apps/spotlight/src/pages/index.astro

Updated the demo link to point to a new form.
The form collects:
- Name (required)
- Title (required)
- Email address (required)
- Agency (required)
- Comments

update link for demo request form

---

apps/spotlight/src/pages/index.astro

- Remove stubbed content and replace with more representative features and value props
- Remove testimonials
- Adjust style to reflect digital.gov style guide
[Preview](https://federalist-9ab3a388-1535-4bd5-a4bf-04c7933172d6.sites.pages.cloud.gov/preview/gsa-tts/forms/jd-splash-copy-updates/)

Splash page copy and layout updates

---

packages/common/src/locales/en/app.ts
packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
packages/design/src/FormManager/FormEdit/components/AttachmentPatternEdit/AttachmentPatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/AttachmentPatternEdit/attachmentPatternEditStyles.module.css
packages/design/src/FormManager/FormEdit/components/AttachmentPatternEdit/index.tsx
packages/design/src/FormManager/FormEdit/components/FieldsetEdit/FieldsetEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/FieldsetEdit/index.tsx
packages/design/src/FormManager/FormEdit/components/FormSummaryEdit.tsx
packages/design/src/FormManager/FormEdit/formEditStyles.module.css
packages/forms/src/patterns/rich-text.ts

**Overview**
- Removes package downloads from add component menu dropdown\
- Removes PatternActions (ability to delete) Form Title component
- Relabel the question input field to ‘Question text’ for attachment component
- Styles (widens) the question input field for attachment component, and form title component
- Hide the configuration options for allowable file types and max number of files in attachment component

feat: updates UI components

---

e2e/src/create.spec.ts
e2e/src/edit.spec.ts
packages/design/src/FormManager/FormEdit/FormEdit.stories.tsx
test-runner.js

**Changes Included**
***e2e Tests:***
> Ensured the createNewForm function navigates to the correct URL and clicks the "Create New" button.
> Updated the addQuestions function to correctly add "Short answer" and "Multiple choice" questions and fill in the labels.
> Added checks to verify the correct order of items after the drag-and-drop action.
***Storybook Tests:***
> Fixed the FormEditAddPattern story to correctly add a new pattern and save it.
> Updated the FormEditReorderPattern story to ensure patterns are reordered correctly.
**Ticket Reference**
These changes address the requirements outlined in ticket [TCKT-555](https://github.com/GSA-TTS/forms/issues/555).

fix(tests): resolve failing e2e Playwright and Storybook tests in CI for Main branch TCKT-555

---

Dockerfile

This should fix a Docker build error that I introduced.

Fix package name filter in docker build

---

packages/common/src/locales/en/app.ts
packages/design/src/Form/components/AccordionRow/AccordionRow.stories.tsx
packages/design/src/Form/components/AccordionRow/index.tsx
packages/design/src/Form/components/index.tsx
packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
packages/design/src/FormManager/FormEdit/components/AccordionRowPatternEdit/AccordionRowPatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/AccordionRowPatternEdit/index.tsx
packages/design/src/FormManager/FormEdit/components/index.ts
packages/forms/src/components.ts
packages/forms/src/patterns/accordion-row/accordion-row.test.ts
packages/forms/src/patterns/accordion-row/index.ts
packages/forms/src/patterns/checkbox.ts
packages/forms/src/patterns/index.ts
packages/forms/src/patterns/input/index.ts
packages/forms/src/patterns/radio-group.ts
packages/forms/src/patterns/select-dropdown/select-dropdown.ts
packages/forms/src/patterns/text-area/text-area.ts

**Key Changes:**
***Component:***
Created a new AccordionRow and AccordionRow Edit components so that additional content can be hidden/revealed when selected.
Included accessibility features such as ARIA attributes for better screen reader support.
***Storybook:***
Added Storybook stories for both the Accordion Row and component to demonstrate its usage and variations.
***Tests:***
Added unit tests to validate the functionality of the Accordion Row and AccordionRow Edit component.
***Refactoring:***
Updated default question text values for multiple standalone components.
Ticket Reference: [TCKT-523](https://github.com/GSA-TTS/forms/issues/523)

feat: create accordion row pattern TCKT-523

---

e2e/package.json
e2e/src/fixtures/add-download.fixture.ts
e2e/src/form-filler.spec.ts
e2e/src/models/form-filler-page.ts
pnpm-lock.yaml

- **add package download fixture**
- **click next recursively in test**
- **refactor test**
- **verify form field value exists**
- **extract methods in test**

PDF verification end-to-end test

---

packages/design/src/FormManager/FormEdit/components/common/story-helper.tsx
packages/forms/src/builder/builder.test.ts
packages/forms/src/patterns/form-summary/form-summary.test.ts
packages/forms/src/patterns/form-summary/form-summary.ts

*Overview*
This PR updates forms-summary description placeholder
*References*
TCKT: #621

update form summary description placeholder

---

packages/common/src/locales/en/app.ts
packages/design/src/Form/components/Date/Date.stories.tsx
packages/design/src/Form/components/Date/Date.tsx
packages/design/src/Form/components/Date/index.tsx
packages/design/src/Form/components/DateOfBirth/index.tsx
packages/design/src/Form/components/Fieldset/Fieldset.stories.tsx
packages/design/src/Form/components/Repeater/Repeater.stories.tsx
packages/design/src/Form/components/index.tsx
packages/design/src/FormManager/FormEdit/AddPatternDropdown.tsx
packages/design/src/FormManager/FormEdit/components/DatePatternEdit/DatePatternEdit.stories.tsx
packages/design/src/FormManager/FormEdit/components/DatePatternEdit/index.tsx
packages/design/src/FormManager/FormEdit/components/EmailInputPatternEdit/index.tsx
packages/design/src/FormManager/FormEdit/components/common/story-helper.tsx
packages/design/src/FormManager/FormEdit/components/index.ts
packages/forms/src/components.ts
packages/forms/src/patterns/date-of-birth/date-of-birth.ts
packages/forms/src/patterns/date-picker/date-picker.test.ts
packages/forms/src/patterns/date-picker/date-picker.ts
packages/forms/src/patterns/index.ts

**Summary:** 
This PR updates the existing "DOB" (Date of Birth) pattern to a more generic "Date" pattern and introduces a new Date Picker configuration. The changes include updates to imports, types, tests, and configuration files to reflect the new naming and functionality.
**Key Changes:**
***Refactor:***
> Renamed "DOB" pattern to "Date" pattern across the codebase.
> Updated configuration files to align with the new "Date" pattern.
> Updated imports in multiple files to reflect the component name change from "DOB" to "Date."
***Feature:***
> Added a new configuration file for the Date Picker pattern.
> Updated dropdown menus to include the Date Picker pattern.
***Tests:***
> Added configuration tests for the Date Picker pattern.
**Ticket:** …

feat: update DOB Pattern to Date Pattern and add Date Picker Configuration (TCKT-572)

---

e2e/src/preview.spec.ts
packages/design/src/Form/components/PageSet/PageMenu/PageMenu.tsx
packages/design/src/Form/components/PageSet/PageSet.tsx
packages/design/src/FormManager/FormEdit/components/common/story-helper.tsx
packages/design/src/FormManager/FormPreview/index.tsx
packages/design/src/FormManager/index.tsx

- add session info to preview
- update pagemenu logic for selected
- add e2e test for preview
closes #565

Form preview page navigation
